### ISSUE TITLE
automating Postie setup

### ISSUE THREAD

**Issue by grizzlysmit** [raamdev/postie#2]
is there any way I can automate my postie setup, I have several instances to setup and I want to do it with a script or similar to save time

**Comment by raamdev** [comment]
Hey @grizzlysmit, 

As per the [README](https://github.com/raamdev/postie):

> The [Postie WordPress Plugin](http://wordpress.org/extend/plugins/postie/) maintainer has merged the changes from this fork into the main release of Postie. As of Postie v1.4.6 (2012.12.06), Custom Post Types can be specified via the email subject. 
> 
> This fork is no longer maintained. For the latest version of Postie, please see the main [plugin page](http://wordpress.org/extend/plugins/postie/).

Unfortunately I don't have an answer to your question, but you may want to try asking on the [Postie support forum](https://wordpress.org/support/plugin/postie/).
